---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto 
spec:
  type: NodePort 
  selector:
    app: mosquitto 
  ports: 
  - name: "tcp-port" 
    port: 1883 
    targetPort: 1883 
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.168.0.223
