---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto 
    spec:
      containers:
      - name: mosquitto 
        image: eclipse-mosquitto:latest  
        imagePullPolicy: "Always"
        ports:
        - containerPort: 1883
          name: "tcp-port" 
          protocol: TCP
        volumeMounts:
        - name: k8s-pv01
          mountPath: mosquitto/config
          subPath: mosquitto/config
        - name: k8s-pv01
          mountPath: mosquitto/data
          subPath: mosquitto/data
        - name: k8s-pv01
          mountPath: mosquitto/log
          subPath: mosquitto/log
      volumes:
      - name: k8s-pv01 
        persistentVolumeClaim:
          claimName: synology-k8s-pv01
